# PostgreSQL ?????
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_db
spring.datasource.username=postgres
spring.datasource.password=123456

# MyBatis-Plus SQL ?????????? SQL?
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0